server:
  port: 8080

spring:
  application:
    name: MEDIC-API
  datasource:
    url: jdbc:mysql://localhost:3306/user_ms
    username: root
    password: root
    driver: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect